language: ruby

addons:
  chrome: stable

before_install:
  - sudo apt update -qq
  - sudo apt install -y chromium-chromedriver
  - gem i bundler -v '<2'

cache: bundler

# rvm:
#   - 2.6.6
#   - 2.5.8
#   - 2.4.6
#   - 2.3.8
#   - 2.2.10
#   - 2.1.10
#   - 2.0.0
# gemfile:
#   - gemfiles/Gemfile-rails.5.2.x
#   - gemfiles/Gemfile-rails.5.1.x
#   - gemfiles/Gemfile-rails.5.0.x
#   - gemfiles/Gemfile-rails.4.2.x

matrix:
  include:
    - rvm: 2.7.1
      gemfile: gemfiles/Gemfile-rails.6.1.x
    - rvm: 2.7.1
      gemfile: gemfiles/Gemfile-rails.6.1.x
      env: API=1
    - rvm: 2.7.1
      gemfile: gemfiles/Gemfile-rails.6.0.x
    - rvm: 2.7.1
      gemfile: gemfiles/Gemfile-rails.6.0.x
      env: API=1

    - rvm: 2.6.6
      gemfile: gemfiles/Gemfile-rails.6.1.x
    - rvm: 2.6.6
      gemfile: gemfiles/Gemfile-rails.6.1.x
      env: API=1
    - rvm: 2.6.6
      gemfile: gemfiles/Gemfile-rails.6.0.x
    - rvm: 2.6.6
      gemfile: gemfiles/Gemfile-rails.6.0.x
      env: API=1
    - rvm: 2.6.6
      gemfile: gemfiles/Gemfile-rails.5.2.x
    - rvm: 2.6.6
      gemfile: gemfiles/Gemfile-rails.5.2.x
      env: API=1
    - rvm: 2.6.6
      gemfile: gemfiles/Gemfile-rails.5.1.x
    - rvm: 2.6.6
      gemfile: gemfiles/Gemfile-rails.5.1.x
      env: API=1
    - rvm: 2.6.6
      gemfile: gemfiles/Gemfile-rails.5.0.x
    - rvm: 2.6.6
      gemfile: gemfiles/Gemfile-rails.5.0.x
      env: API=1

    - rvm: 2.5.8
      gemfile: gemfiles/Gemfile-rails.5.2.x

    - rvm: 2.4.6
      gemfile: gemfiles/Gemfile-rails.5.2.x

    - rvm: 2.3.8
      gemfile: gemfiles/Gemfile-rails.5.2.x
    - rvm: 2.3.8
      gemfile: gemfiles/Gemfile-rails.4.2.x

    - rvm: 2.2.10
      gemfile: gemfiles/Gemfile-rails.5.2.x

    - rvm: 2.1.10
      gemfile: gemfiles/Gemfile-rails.4.2.x

    - rvm: 2.0.0
      gemfile: gemfiles/Gemfile-rails.4.2.x

    - rvm: ruby-head
      gemfile: gemfiles/Gemfile-rails.edge

    - rvm: ruby-head
      gemfile: gemfiles/Gemfile-rails.edge
      env: API=1

  allow_failures:
    - rvm: ruby-head
    - gemfile: gemfiles/Gemfile-rails.edge
